# Generated by Django 4.2.8 on 2023-12-30 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_todolist_todos_user_todos_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='shared_link',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='user',
        ),
        migrations.AddField(
            model_name='todolist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todolist_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SharedTodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TodoList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='todolist',
            name='user',
            field=models.ManyToManyField(related_name='todolist_user', through='todo.SharedTodoList', to=settings.AUTH_USER_MODEL),
        ),
    ]
