# Generated by Django 4.2.8 on 2023-12-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_sharedtodolist_todolist_remove_todos_todolist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedtodolist',
            old_name='todo_list',
            new_name='todolist',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='todo_list',
            new_name='todolist',
        ),
    ]
