# Generated by Django 4.2.8 on 2023-12-31 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0007_rename_todo_list_sharedtodolist_todolist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtodolist',
            name='title',
            field=models.CharField(default='Default title', max_length=100),
        ),
        migrations.AlterField(
            model_name='sharedtodolist',
            name='todolist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.todolist'),
        ),
        migrations.AlterField(
            model_name='sharedtodolist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todos',
            name='todolist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo.todolist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todos',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
