# Generated by Django 4.2.8 on 2023-12-31 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_sharedtodolist_title_alter_sharedtodolist_todolist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedtodolist',
            name='todolist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todolist'),
        ),
    ]
